apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ansible-role-dns
  language: ansible
  description: |
    This playbook installs & configure DNS server on RHEL 8 & Suse 15 machine
  annotations:
    gitlab.com/project-slug: pes/sap
    backstage.io/techdocs-ref: dir:/docs
    backstage.io/managed-by: backstage
  tags:
    - ansible
    - network-utilities
    - install
    - aws
    - azure
    - ibmcloud
spec:
  type: Source Control
  owner: group:ansible-code-manager
  lifecycle: production
  dependencies:
    - type: repo
      target: https://github.com/org/repository-a
      relationship: depends-on
    - type: repo
      target: https://github.com/org/repository-b
      relationship: uses
